In [1]:
import tensorflow as tf

##### Building computational graph(constant)

In [12]:
a = tf.constant(3.0, dtype = tf.float32)
b = tf.constant(4.0)
total = a + b
print(a)
print(b)
print(total)

Tensor("Const_1:0", shape=(), dtype=float32)
Tensor("Const_2:0", shape=(), dtype=float32)
Tensor("add_1:0", shape=(), dtype=float32)


In [13]:
a = tf.constant([3.0, 4.0], dtype = tf.float32)
print(a)

Tensor("Const_3:0", shape=(2,), dtype=float32)


##### running computational graph(constant)

In [14]:
a = tf.constant(3.0, dtype = tf.float32)
b = tf.constant(4.0)
total = a + b

sess = tf.Session()
print(sess.run(total))
print(sess.run([a,b]))
sess.close()

7.0
[3.0, 4.0]


In [15]:
a = tf.constant([3.0, 4.0], dtype = tf.float32)

sess = tf.Session()
print(sess.run(a))
sess.close()

[3. 4.]


##### building computational graph(placeholder)

In [16]:
x = tf.placeholder(tf.float32)
y = tf.placeholder(tf.float32)
z = x + y
print(x)
print(y)
print(z)

Tensor("Placeholder_1:0", dtype=float32)
Tensor("Placeholder_2:0", dtype=float32)
Tensor("add_3:0", dtype=float32)


In [17]:
x1 = tf.placeholder(tf.float32, shape = [2])
y1 = tf.placeholder(tf.float32, shape = [2])
z1 = x1 + y1
print(x1)
print(y1)
print(z1)

Tensor("Placeholder_3:0", shape=(2,), dtype=float32)
Tensor("Placeholder_4:0", shape=(2,), dtype=float32)
Tensor("add_4:0", shape=(2,), dtype=float32)


##### running computational graph(placeholder)

In [18]:
x = tf.placeholder(tf.float32)
y = tf.placeholder(tf.float32)
z = x + y

sess = tf.Session()
print(sess.run(z, feed_dict = {x: 3.5, y: 4})) #feed_dict: 필요한 값을 넣어줌
sess.close()

7.5


In [19]:
x1 = tf.placeholder(tf.float32, shape = [2])
y1 = tf.placeholder(tf.float32, shape = [2])
z1 = x1 + y1

sess = tf.Session()
print(sess.run(z1, feed_dict = {x1: [1,3], y1 : [2,4]}))
sess.close()

[3. 7.]


##### building computational graph(variable)

In [2]:
my_variable = tf.Variable("my_variable", [1,2,3])
print(my_variable)

<tf.Variable 'Variable:0' shape=() dtype=string_ref>


In [3]:
my_variable = tf.get_variable("my_variable", [1,2,3])
my_int_variable = tf.get_variable("my_int_variable", [1,2,3], dtype = tf.int32, initializer = tf.zeros_initializer)
print(my_variable)
print(my_int_variable)

W0823 15:27:45.917676 140549866198784 deprecation.py:506] From /home/pirl/anaconda3/envs/tens/lib/python3.7/site-packages/tensorflow/python/ops/init_ops.py:1251: calling VarianceScaling.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor


<tf.Variable 'my_variable:0' shape=(1, 2, 3) dtype=float32_ref>
<tf.Variable 'my_int_variable:0' shape=(1, 2, 3) dtype=int32_ref>


In [4]:
my_variable = tf.Variable("my_variable", [1])
dup = tf.get_variable("my_variable", [1])

ValueError: Variable my_variable already exists, disallowed. Did you mean to set reuse=True or reuse=tf.AUTO_REUSE in VarScope? Originally defined at:

  File "<ipython-input-3-e088f35061da>", line 1, in <module>
    my_variable = tf.get_variable("my_variable", [1,2,3])
  File "/home/pirl/anaconda3/envs/tens/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3325, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "/home/pirl/anaconda3/envs/tens/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3248, in run_ast_nodes
    if (await self.run_code(code, result,  async_=asy)):
  File "/home/pirl/anaconda3/envs/tens/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3057, in run_cell_async
    interactivity=interactivity, compiler=compiler, result=result)
  File "/home/pirl/anaconda3/envs/tens/lib/python3.7/site-packages/IPython/core/async_helpers.py", line 68, in _pseudo_sync_runner
    coro.send(None)


In [5]:
v = tf.get_variable('v', [1,2,3], dtype = tf.float32)

sess = tf.Session()
sess.run(tf.global_variables_initializer())
print(sess.run(v))

[[[ 0.37602568  0.9466374  -0.22124797]
  [-0.85917604  0.37785733 -0.64459765]]]


In [10]:
v1 = tf.get_variable('v1', [1,2,3], dtype = tf.int32, 
                     initializer = tf.zeros_initializer)
v2 = tf.get_variable('v2', [1,2,3], dtype = tf.float32, 
                     initializer = tf.constant_initializer(1.0))
sess = tf.Session()
sess.run(tf.global_variables_initializer())
o1, o2 =sess.run([v1, v2])
print(o1)
print(o2)

[[[0 0 0]
  [0 0 0]]]
[[[1. 1. 1.]
  [1. 1. 1.]]]


In [15]:
v1 = tf.get_variable('v1', [1,2,3], dtype = tf.int32, 
                     initializer = tf.zeros_initializer)
v2 = tf.get_variable('v2', [1,2,3], dtype = tf.float32, 
                     initializer = tf.constant_initializer(1.0))
sess = tf.Session()
sess.run(tf.global_variables_initializer())
o1, o2 =sess.run([v1, v2])
print(o1)
print(o2)

[[[0 0 0]
  [0 0 0]]]
[[[1. 1. 1.]
  [1. 1. 1.]]]


#### difference between Variable and get_variable

##### Variable: 변수 선언 시 마다 새로운 변수를 생성
늦게 생성된 것을 기준으로 사용

In [20]:
my_variable = tf.Variable("my_variable", [1,2,3])
print(my_variable)

<tf.Variable 'Variable_2:0' shape=() dtype=string_ref>


In [21]:
my_variable = tf.Variable("my_variable", [1,2,3])
print(my_variable)

<tf.Variable 'Variable_3:0' shape=() dtype=string_ref>


In [22]:
my_variable = tf.Variable("my_variable", [1,2,3])
print(my_variable)

<tf.Variable 'Variable_4:0' shape=() dtype=string_ref>


##### get_variable: 변수가 없을 경우에만 새롭게 생성
get_variable을 사용하는 것이 더 나은 경우가 많다

In [16]:
with tf.variable_scope('foo'):
    my_variable = tf.get_variable('my_variable', [1])
with tf.variable_scope('foo', reuse = True):
    dup = tf.get_variable('my_variable', [1])
    
print(my_variable)
print(dup)

<tf.Variable 'foo/my_variable:0' shape=(1,) dtype=float32_ref>
<tf.Variable 'foo/my_variable:0' shape=(1,) dtype=float32_ref>


In [17]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    print(sess.run(my_variable))
    print(sess.run(dup))

[0.3322245]
[0.3322245]


In [19]:
with tf.variable_scope('foo'):
    my_variable = tf.get_variable('my_variable', [1])
with tf.variable_scope('bar'):
    dup = tf.get_variable('my_variable', [1])
    
print(my_variable)
print(dup)

<tf.Variable 'foo/my_variable:0' shape=(1,) dtype=float32_ref>
<tf.Variable 'bar/my_variable:0' shape=(1,) dtype=float32_ref>


#### Examples

In [5]:
#1
x = tf.placeholder(tf.float32)
w = tf.get_variable("w", initializer = tf.constant([2.]))
b = tf.constant(4.0)
y = x * w + b

print(x)
print(w)
print(b)
print(y)

sess = tf.Session()
sess.run(tf.global_variables_initializer())
print(sess.run(y, feed_dict = {x:1}))

Tensor("Placeholder:0", dtype=float32)
<tf.Variable 'w:0' shape=(1,) dtype=float32_ref>
Tensor("Const_1:0", shape=(), dtype=float32)
Tensor("add:0", dtype=float32)
[6.]


In [25]:
#2
x = tf.placeholder(tf.float32, shape = [1])
w = tf.get_variable("w",shape = [1], initializer = tf.zeros_initializer)
b = tf.constant([4.0])
y = x * w + b

print(x)
print(w)
print(b)
print(y)

sess = tf.Session()
sess.run(tf.global_variables_initializer())
print(sess.run(y, feed_dict = {x:[1]}))

Tensor("Placeholder:0", shape=(1,), dtype=float32)
<tf.Variable 'w:0' shape=(1,) dtype=float32_ref>
Tensor("Const:0", shape=(1,), dtype=float32)
Tensor("add:0", shape=(1,), dtype=float32)
[4.]


In [27]:
#3
import numpy as np
tf.reset_default_graph()
x = tf.placeholder(tf.float32, shape = [None, 2])
w = tf.get_variable("w", shape = [2], initializer = tf.random_normal_initializer())
y = x * w

print(x)
print(w)
print(y)

sess = tf.Session()
sess.run(tf.global_variables_initializer())
print(sess.run(y, feed_dict = {x: np.random.rand(3,2)}))

Tensor("Placeholder:0", shape=(?, 2), dtype=float32)
<tf.Variable 'w:0' shape=(2,) dtype=float32_ref>
Tensor("mul:0", shape=(?, 2), dtype=float32)
[[ 0.44441935 -0.49050108]
 [ 0.33835554 -0.70173746]
 [ 0.41477942 -0.504966  ]]
