In [0]:
import tensorflow as tf

### SoftMax

In [0]:
tf.set_random_seed(1123)

In [0]:
x_data = [[1, 2, 1],
          [1, 3, 2],
          [1, 3, 4],
          [1, 5, 5],
          [1, 7, 5],
          [1, 2, 5],
          [1, 6, 6],
          [1, 7, 7]]
y_data = [[0, 0, 1],
          [0, 0, 1],
          [0, 0, 1],
          [0, 1, 0],
          [0, 1, 0],
          [0, 1, 0],
          [1, 0, 0],
          [1, 0, 0]]


In [0]:
x_test = [[2, 1, 1],
          [3, 1, 2],
          [3, 3, 4]]
y_test = [[0, 0, 1],
          [0, 0, 1],
          [0, 0, 1]]

In [0]:
x = tf.placeholder('float',[None,3])
y = tf.placeholder('float',[None,3])
w = tf.Variable(tf.random_normal([3,3]))
b = tf.Variable(tf.random_normal([3]))

In [0]:
hypothesis = tf.nn.softmax(tf.matmul(x,w) + b)
cost = tf.reduce_mean(-tf.reduce_sum(y*tf.log(hypothesis), axis = 1))
optimizer = tf.train.GradientDescentOptimizer(learning_rate = 0.1).minimize(cost)

In [0]:
prediction = tf.arg_max(hypothesis, 1)
is_correct = tf.equal(prediction, tf.arg_max(y, 1))
accuracy = tf.reduce_mean(tf.cast(is_correct, tf.float32))

In [34]:
with tf.Session() as sess:
  sess.run(tf.global_variables_initializer())
  for step in range(201):
    cost_val, w_val, _ = sess.run([cost, w, optimizer], feed_dict = {x: x_data, y: y_data})
    print(step, cost_val, w_val)
    
  print('Prediction:', sess.run(prediction, feed_dict = {x: x_data}))
  print('Accuracy:', sess.run(accuracy, feed_dict = {x:x_test, y:y_test}))

0 3.7114902 [[ 1.1466843   0.08229703  0.7401341 ]
 [ 1.7133249   1.0502092   0.02695014]
 [-0.41171816 -0.2794451   0.57012826]]
1 2.0333257 [[ 1.1043365   0.11625947  0.7485194 ]
 [ 1.530235    1.2133348   0.04691439]
 [-0.55905294 -0.10243221  0.54045016]]
2 1.2387166 [[ 1.09736     0.12339723  0.74835813]
 [ 1.5354339   1.2278937   0.02715671]
 [-0.53034407 -0.06366733  0.47297636]]
3 1.1855967 [[ 1.0892608   0.12472451  0.75513005]
 [ 1.537953    1.2137612   0.03876997]
 [-0.5052454  -0.05398558  0.43819594]]
4 1.1633118 [[ 1.0784094   0.12754293  0.76316303]
 [ 1.525167    1.2096843   0.05563294]
 [-0.49459934 -0.03592952  0.40949383]]
5 1.143643 [[ 1.0691721   0.1281909   0.77175236]
 [ 1.5214112   1.194223    0.07484992]
 [-0.47608528 -0.02910404  0.3841543 ]]
6 1.1249087 [[ 1.0584038   0.13029528  0.78041625]
 [ 1.5084434   1.1876194   0.0944214 ]
 [-0.46634752 -0.01452932  0.35984182]]
7 1.1068437 [[ 1.0490556   0.1309105   0.7891493 ]
 [ 1.5030229   1.1731181   0.11434323]
 

In [33]:
with tf.Session() as sess:   
  sess.run(tf.global_variables_initializer())
  print('Prediction:', sess.run(prediction, feed_dict = {x: x_data}))
  print('Accuracy:', sess.run(accuracy, feed_dict = {x:x_test, y:y_test}))

Prediction: [0 0 0 0 0 2 0 0]
Accuracy: 0.33333334


In [0]:
#learning rate 크기 변화
hypothesis = tf.nn.softmax(tf.matmul(x,w) + b)
cost = tf.reduce_mean(-tf.reduce_sum(y*tf.log(hypothesis), axis = 1))
optimizer = tf.train.GradientDescentOptimizer(learning_rate = 1.5).minimize(cost)
prediction = tf.arg_max(hypothesis, 1)
is_correct = tf.equal(prediction, tf.arg_max(y, 1))
accuracy = tf.reduce_mean(tf.cast(is_correct, tf.float32))

In [26]:
with tf.Session() as sess:
  sess.run(tf.global_variables_initializer())
  for step in range(201):
    cost_val, w_val, _ = sess.run([cost, w, optimizer], feed_dict = {x: x_data, y: y_data})
    print(step, cost_val, w_val)
    
  print('Prediction:', sess.run(prediction, feed_dict = {x: x_data}))
  print('Accuracy:', sess.run(accuracy, feed_dict = {x:x_test, y:y_test}))

0 12.316021 [[-0.9072083   0.71875906 -1.4382908 ]
 [ 3.2103608   0.7278266  -3.6660085 ]
 [ 2.0749493   1.292052   -4.9116178 ]]
1 nan [[nan nan nan]
 [nan nan nan]
 [nan nan nan]]
2 nan [[nan nan nan]
 [nan nan nan]
 [nan nan nan]]
3 nan [[nan nan nan]
 [nan nan nan]
 [nan nan nan]]
4 nan [[nan nan nan]
 [nan nan nan]
 [nan nan nan]]
5 nan [[nan nan nan]
 [nan nan nan]
 [nan nan nan]]
6 nan [[nan nan nan]
 [nan nan nan]
 [nan nan nan]]
7 nan [[nan nan nan]
 [nan nan nan]
 [nan nan nan]]
8 nan [[nan nan nan]
 [nan nan nan]
 [nan nan nan]]
9 nan [[nan nan nan]
 [nan nan nan]
 [nan nan nan]]
10 nan [[nan nan nan]
 [nan nan nan]
 [nan nan nan]]
11 nan [[nan nan nan]
 [nan nan nan]
 [nan nan nan]]
12 nan [[nan nan nan]
 [nan nan nan]
 [nan nan nan]]
13 nan [[nan nan nan]
 [nan nan nan]
 [nan nan nan]]
14 nan [[nan nan nan]
 [nan nan nan]
 [nan nan nan]]
15 nan [[nan nan nan]
 [nan nan nan]
 [nan nan nan]]
16 nan [[nan nan nan]
 [nan nan nan]
 [nan nan nan]]
17 nan [[nan nan nan]
 [nan nan

### Normalization

In [0]:
import numpy as np

In [0]:
xy = np.array([[828.659973, 833.450012, 908100, 828.349976, 831.659973],
               [823.02002, 828.070007, 1828100, 821.655029, 828.070007],
               [819.929993, 824.400024, 1438100, 818.97998, 824.159973],
               [816, 820.958984, 1008100, 815.48999, 819.23999],
               [819.359985, 823, 1188100, 818.469971, 818.97998],
               [819, 823, 1198100, 816, 820.450012],
               [811.700012, 815.25, 1098100, 809.780029, 813.669983],
               [809.51001, 816.659973, 1398100, 804.539978, 809.559998]])

In [0]:
x_data = xy[:,0:-1]
y_data = xy[:, [-1]]  #[-1]을 적어서 (8,1) 행렬이 됨. 아니면 (1,8)

In [40]:
x_data

array([[8.28659973e+02, 8.33450012e+02, 9.08100000e+05, 8.28349976e+02],
       [8.23020020e+02, 8.28070007e+02, 1.82810000e+06, 8.21655029e+02],
       [8.19929993e+02, 8.24400024e+02, 1.43810000e+06, 8.18979980e+02],
       [8.16000000e+02, 8.20958984e+02, 1.00810000e+06, 8.15489990e+02],
       [8.19359985e+02, 8.23000000e+02, 1.18810000e+06, 8.18469971e+02],
       [8.19000000e+02, 8.23000000e+02, 1.19810000e+06, 8.16000000e+02],
       [8.11700012e+02, 8.15250000e+02, 1.09810000e+06, 8.09780029e+02],
       [8.09510010e+02, 8.16659973e+02, 1.39810000e+06, 8.04539978e+02]])

In [46]:
y_data

array([[831.659973],
       [828.070007],
       [824.159973],
       [819.23999 ],
       [818.97998 ],
       [820.450012],
       [813.669983],
       [809.559998]])

In [0]:
x = tf.placeholder(tf.float32, shape=[None, 4])
y = tf.placeholder(tf.float32, shape = [None,1])
w = tf.Variable(tf.random_normal([4,1]), name = 'weight')
b = tf.Variable(tf.random_normal([1]), name = 'bias')

In [0]:
hypothesis = tf.matmul(x, w) + b
cost = tf.reduce_mean(tf.square(hypothesis - y))

In [0]:
optimizer = tf.train.GradientDescentOptimizer(learning_rate = 1.5).minimize(cost)

In [53]:
with tf.Session() as sess:
  sess.run(tf.global_variables_initializer())
  for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, optimizer], feed_dict = {x:x_data, y:y_data})
    print(step, 'Cost: ', cost_val,"\nPrediction\n", hy_val)

0 Cost:  284895480000.0 
Prediction
 [[-376410.56]
 [-756258.25]
 [-595224.9 ]
 [-417677.6 ]
 [-491999.28]
 [-496126.66]
 [-454824.66]
 [-578695.2 ]]
1 Cost:  7.0427e+36 
Prediction
 [[1.8719787e+18]
 [3.7684851e+18]
 [2.9645313e+18]
 [2.0781207e+18]
 [2.4491762e+18]
 [2.4697904e+18]
 [2.2636484e+18]
 [2.8820745e+18]]
2 Cost:  inf 
Prediction
 [[-9.3073887e+30]
 [-1.8736728e+31]
 [-1.4739508e+31]
 [-1.0332317e+31]
 [-1.2177187e+31]
 [-1.2279680e+31]
 [-1.1254751e+31]
 [-1.4329537e+31]]
3 Cost:  inf 
Prediction
 [[inf]
 [inf]
 [inf]
 [inf]
 [inf]
 [inf]
 [inf]
 [inf]]
4 Cost:  inf 
Prediction
 [[-inf]
 [-inf]
 [-inf]
 [-inf]
 [-inf]
 [-inf]
 [-inf]
 [-inf]]
5 Cost:  nan 
Prediction
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
6 Cost:  nan 
Prediction
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
7 Cost:  nan 
Prediction
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
8 Cost:  nan 
Prediction
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
9 C

In [0]:
#Normalization
def MinMaxScaler(data):
  numerator = data - np.min(data,0)
  denominator = np.max(data,0) - np.min(data,0)
  
  return numerator/(denominator+1e-7)

In [58]:
xy = MinMaxScaler(xy)
print(xy)

[[0.99999999 0.99999999 0.         1.         1.        ]
 [0.70548491 0.70439552 1.         0.71881782 0.83755791]
 [0.54412549 0.50274824 0.57608696 0.606468   0.6606331 ]
 [0.33890353 0.31368023 0.10869565 0.45989134 0.43800918]
 [0.51436    0.42582389 0.30434783 0.58504805 0.42624401]
 [0.49556179 0.42582389 0.31521739 0.48131134 0.49276137]
 [0.11436064 0.         0.20652174 0.22007776 0.18597238]
 [0.         0.07747099 0.5326087  0.         0.        ]]
